receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  debug:
    verbosity: detailed
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin, elasticsearch, debug]
    logs:
      receivers: [otlp]
      exporters: [elasticsearch, debug]
