global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8000']
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8000']
  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:8000']
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8000']
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8000']